#!/usr/bin/env python3
"""Rank what is blocking each non-emittable instruction, closest-first.

The emittability headline says how many instructions an implementer can emit.
This says WHICH FIELD to sweep next to move it, which is the question an agent
dispatch actually needs answered. Regenerate after every merge:

    python3 tools/agx-isa/emit_worklist.py > docs/isa/emit-worklist.md

CLEAN-ROOM: pure analysis over our own db.json + validation.json.
"""
import collections, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
D = os.path.join(ROOT, "tools", "agx-isa")
EMIT = {"hardware-run", "isolated-byte-diff"}
DATA_WORD_ROLE = "data-word"


def main():
    db = json.load(open(os.path.join(D, "db.json")))
    val = json.load(open(os.path.join(D, "validation.json")))
    rel = [i for i in db["instructions"] if i.get("emitter_role") != DATA_WORD_ROLE]
    blocked, emittable = [], []
    for i in rel:
        m = i["mnemonic"]
        names = [f["name"] for f in i.get("fields", [])]
        entry = val["instructions"].get(m, {})
        note = (entry.get("_instruction") or {}).get("note", "") or ""
        veto = "EMITTABLE VETO" in note
        bl = [(n, entry.get(n, {}).get("label", "MISSING")) for n in names
              if entry.get(n, {}).get("label") not in EMIT]
        # The _instruction gate. An instruction is NOT emittable just because
        # every named field passes: the instruction-level label carries the
        # claim that the opcode/match bits themselves were exercised. Omitting
        # this over-counted by 5 (37 vs 32) and, worse, pointed a dispatcher at
        # field sweeps for instructions that were already field-complete and
        # blocked somewhere else entirely.
        inst_label = (entry.get("_instruction") or {}).get("label", "MISSING")
        if inst_label not in EMIT:
            bl.append(("_instruction", inst_label))
        if bl or veto or not names:
            blocked.append((len(bl), m, bl, veto, bool(names)))
        else:
            emittable.append(m)
    blocked.sort(key=lambda r: (r[0], r[1]))

    out = sys.stdout
    out.write("# Emitter worklist — what to sweep next\n\n")
    out.write("**Generated by `tools/agx-isa/emit_worklist.py`; do not hand-edit.**\n\n")
    out.write('> ### ⚠ THE COUNT BELOW IS A LABEL COUNT, NOT AN EMITTABILITY PROOF\n>\n> `RE_EXPERIMENT_PROCESS_CORRECTIONS.md` §2: **"`emittable` additionally requires a complete\n> generated recipe. Field labels alone are not an emittability proof."** The §8 promotion checker\n> (`tools/agx-isa/promotion_check.py`), which opens the cited raw instead of trusting the citation,\n> **blocks every emitter-grade row in the corpus, and 0 of the mnemonics counted below have all\n> their rows clear.** The recipe dashboard reads **2 of 166 canonical-recipe-proven**.\n>\n> Read this file as what it is: a **sweep-ordering aid** — which field to attack next to move a\n> descriptor along the *liveness* and *geometry* dashboards. It is NOT a completeness measure and\n> must not be quoted as one. Run `python3 tools/agx-isa/dashboards.py` for the accounting, and\n> `promotion_check.py` before believing any row is done.\n>\n> The promotion bar is now the five gates (A actual-byte ledger · B pre-registered\n> detection-power control · C independent semantic predictor · D generated recipe with no donor ·\n> E clean confirmation on a quiet machine), not the two-run agreement rule quoted below — which\n> remains necessary but is no longer sufficient.\n\nThis file answers the question a dispatch actually needs: *which field do I sweep to move the next descriptor forward.* Ordered closest-first.\n\n')
    out.write("A field is emitter-grade only at `hardware-run` or `isolated-byte-diff` "
              "(`docs/evidence-classification.md`). Promotion requires two gated runs at **>=99%% "
              "per-value cross-run agreement AND movement >= 2x the disagreement count** — and a "
              "field that never moves is only promotable if the carriers differ **in the dimension "
              "the field controls**. Two carriers identical in that dimension are one carrier "
              "(EXP-0164; `iter_at.loc` read inert only because every carrier was `samples=1`).\n\n")
    out.write("| emitter-grade LABELS (not proof) | blocked | total emitter-relevant |\n|---:|---:|---:|\n")
    out.write("| %d | %d | %d |\n\n" % (len(emittable), len(blocked), len(rel)))

    dist = collections.Counter(r[0] for r in blocked)
    out.write("## Distance to a full set of emitter-grade labels\n\n| blocking fields | instructions |\n|---:|---:|\n")
    for k in sorted(dist):
        out.write("| %d | %d |\n" % (k, dist[k]))

    fn = collections.Counter()
    for _, _, bl, _, _ in blocked:
        for n, _lab in bl:
            fn[n] += 1
    out.write("\n## Most load-bearing field NAMES\n\n")
    out.write("Sweeping one of these once, on a carrier that generalizes, moves many descriptors.\n\n")
    out.write("| field name | instructions it blocks |\n|---|---:|\n")
    for n, c in fn.most_common(15):
        out.write("| `%s` | %d |\n" % (n, c))

    for dist_n, title in ((1, "ONE field away"), (2, "TWO fields away")):
        rows = [r for r in blocked if r[0] == dist_n]
        if not rows:
            continue
        out.write("\n## %s (%d instructions)\n\n" % (title, len(rows)))
        out.write("| instruction | blocking field(s) | current label |\n|---|---|---|\n")
        for _, m, bl, veto, _hf in rows:
            out.write("| `%s`%s | %s | %s |\n" % (
                m, " **[VETO]**" if veto else "",
                ", ".join("`%s`" % n for n, _ in bl),
                ", ".join(lab for _, lab in bl)))

    out.write("\n## Blocked by a descriptor problem, not a sweep\n\n")
    for _, m, bl, veto, hasf in blocked:
        if veto or not hasf:
            why = "EMITTABLE VETO" if veto else "zero fields modelled — nothing to synthesize"
            out.write("- `%s` — %s\n" % (m, why))

    lab = collections.Counter(l for _, _, bl, _, _ in blocked for _, l in bl)
    only_inst = [(m, bl[0][1]) for _, m, bl, veto, hn in blocked
                 if hn and not veto and len(bl) == 1 and bl[0][0] == "_instruction"]
    if only_inst:
        out.write("\n## Field-complete, blocked at the INSTRUCTION level (%d)\n\n"
                  % len(only_inst))
        out.write("Every named field is emitter-grade; the instruction-level label is not. "
                  "**These need a different dispatch than a field sweep** — the open question is "
                  "whether the opcode/match bits themselves do what the descriptor claims, so the "
                  "probe is to emit the instruction and check it acts, not to vary a field.\n\n")
        out.write("| instruction | `_instruction` label |\n|---|---|\n")
        for m, l in sorted(only_inst):
            out.write("| `%s` | %s |\n" % (m, l))

    out.write("\n## Blocking labels overall\n\n| label | fields |\n|---|---:|\n")
    for l, c in lab.most_common():
        out.write("| `%s` | %d |\n" % (l, c))
    return 0


if __name__ == "__main__":
    sys.exit(main())
